audio_settings:
  buffer_size: 1024
  pyaudio_format: 'paFloat32'
  n_channels: 1
  samplerate: 44100

range_presets:
  Full Range: [20.0, 5000.0]
  Piano Full: [25.0, 4500.0]
  Bass Register: [25.0, 300.0]
  Middle Register: [120.0, 1200.0]
  Treble Register: [400.0, 5000.0]
  A440 Focus: [420.0, 460.0]
  Temperament: [200.0, 800.0]
  Beat Detection: [100.0, 1000.0]
  Unison Tuning: [80.0, 2000.0]
  Cello: [57.0, 240.0]
  Guitar: [75.0, 350.0]

visualizations:
  Main Spectrum:
    default: true
  Pitch Confidence Scatter:
    default: true
  Envelope:
    default: false
  Spectrogram:
    default: false

zmq:
  data_address: 'tcp://127.0.0.1:5555'
  control_address: 'tcp://127.0.0.1:5556'

topics:
  fft:
    payload_type: ndarray
    dtype: float32
    ndim: 2
    max_shape: [2, 8192]
  spectrogram:
    payload_type: ndarray
    dtype: float32
    ndim: 2
    max_shape: [128, 4096]
  string:
    payload_type: str
  analyzer_status:
    payload_type: str
  visualizer_status:
    payload_type: str
  broker_status:
    payload_type: str
